config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :applies
  resources :cprofiles
  devise_for :companies, controllers: { registrations: 'companies/registrations'}
  
  resources :profiles
  devise_for :users, controllers: {registrations: 'users/registrations'}  
  resources :jobs
  root 'pages#index'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
	belongs_to :company
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.company_id = current_company.id

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:role, :description, :company, :apply)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(job) do |f| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<form>
  <div class="form-group">
    <%= f.label :role %>
    <%= f.text_field :role %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>


  <div class="action">
    <%= f.submit %>
  </div>
</form>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Jobs</h1>

<table class="table">
  <thead>
    <tr>
      <th>Role</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.role %></td>
        <td><%= job.description %></td>
        <td><button type="button" class="btn btn-primary"><%= link_to 'Apply', new_apply_path %></button></td>
        <% if company_signed_in? %>
        <td><button type="button" class="btn btn-primary"><%= link_to 'Delete' %></button></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if company_signed_in? %>
  <button type="button" class="btn btn-primary"><%= link_to 'New Job Post', new_job_path %></button></td>
<% end %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p>
  <strong>Role:</strong>
  <%= @job.role %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Company:</strong>
  <%= @job.company_id %>
</p>



<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>