config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :applies
  resources :cprofiles
  devise_for :companies, controllers: { registrations: 'companies/registrations'}
  
  resources :profiles
  devise_for :users, controllers: {registrations: 'users/registrations'}  
  resources :jobs
  root 'pages#index'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_nav.html.erb
 <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Start Fresh</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %>
        <li><%= link_to 'About Us', pages_about_path %>
        <li><%= link_to 'Contact Us', pages_contact_path %>
          <li><%if user_signed_in? || company_signed_in? %>
          <li><%= link_to 'Jobs', jobs_path %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> My Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
                <% if user_signed_in? %>
            <li><%= link_to 'Profile Page', profile_path(current_user.profile) %></li>
                <% end %>
                <% if company_signed_in? %>

            <li><%= link_to 'Company Dashboard', pages_dashboard_path %><li>
            <li><%= link_to 'Profile Page', cprofiles_path %></li>
              <% end %>
            </li>
            <li><%= link_to 'Edit account', edit_user_registration_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
         <% else %>
        <li><%= link_to 'Sign Up', new_user_registration_path %>
        <li><%= link_to 'Login', user_session_path %>
          <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



    