config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :applies
  resources :cprofiles
  devise_for :companies, controllers: { registrations: 'companies/registrations'}
  
  resources :profiles
  devise_for :users, controllers: {registrations: 'users/registrations'}  
  resources :jobs
  root 'pages#index'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cprofile.rb
class Cprofile < ApplicationRecord
	belongs_to :company
end

app/controllers/cprofiles_controller.rb
class CprofilesController < ApplicationController
  before_action :set_cprofile, only: [:show, :edit, :update, :destroy]
  # GET /cprofiles
  # GET /cprofiles.json
  def index
    @cprofiles = Cprofile.all
  end

  # GET /cprofiles/1
  # GET /cprofiles/1.json
  def show
  end

  # GET /cprofiles/new
  def new
    @cprofile = Cprofile.new
    @cprofile.id = current_company.id
  end

  # GET /cprofiles/1/edit
  def edit
  end

  # POST /cprofiles
  # POST /cprofiles.json
  def create
    @cprofile = Cprofile.new(cprofile_params)
    @cprofile.id = current_company.id

    respond_to do |format|
      if @cprofile.save
        format.html { redirect_to cprofile(@cprofile.id), notice: 'Cprofile was successfully created.' }
        format.json { render :show, status: :created, location: @cprofile }
      else
        format.html { render :new }
        format.json { render json: @cprofile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cprofiles/1
  # PATCH/PUT /cprofiles/1.json
  def update
    respond_to do |format|
      if @cprofile.update(cprofile_params)
        format.html { redirect_to cprofile_path(@cprofile.id), notice: 'Cprofile was successfully updated.' }
        format.json { render :show, status: :ok, location: @cprofile }
      else
        format.html { render :edit }
        format.json { render json: @cprofile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cprofiles/1
  # DELETE /cprofiles/1.json
  def destroy
    @cprofile.destroy
    respond_to do |format|
      format.html { redirect_to cprofiles_url, notice: 'Cprofile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cprofile
      @cprofile = Cprofile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cprofile_params
      params.require(:cprofile).permit(:name, :description, :skills)
    end
end

  

app/helpers/cprofiles_helper.rb
module CprofilesHelper
end

app/views/cprofiles/_form.html.erb
<%= form_for(cprofile) do |f| %>
  <% if cprofile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cprofile.errors.count, "error") %> prohibited this cprofile from being saved:</h2>

      <ul>
      <% cprofile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :skills %>
    <%= f.text_area :skills %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cprofiles/edit.html.erb
<h1>Editing Cprofile</h1>

<%= render 'form', cprofile: @cprofile %>

<%= link_to 'Show', @cprofile %> |
<%= link_to 'Back', cprofiles_path %>

app/views/cprofiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cprofiles</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Skills</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cprofiles.each do |cprofile| %>
      <tr>
        <td><%= cprofile.name %></td>
        <td><%= cprofile.description %></td>
        <td><%= cprofile.skills %></td>
        <td><%= link_to 'Show', cprofile %></td>
        <td><%= link_to 'Edit', edit_cprofile_path(cprofile) %></td>
        <td><%= link_to 'Destroy', cprofile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cprofile', new_cprofile_path %>

app/views/cprofiles/new.html.erb
<h1>New Cprofile</h1>

<%= render 'form', cprofile: @cprofile %>

<%= link_to 'Back', cprofiles_path %>

app/views/cprofiles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @cprofile.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cprofile.description %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @cprofile.skills %>
</p>

<%= link_to 'Edit', edit_cprofile_path(@cprofile) %> |
<%= link_to 'Back', cprofiles_path %>